<?php
/**
 * DebitConnectLoginParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VOP\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * V.O.P GmbH & Co. KG - Rest API
 *
 * Rest API-Endpoint
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VOP\Rest;

/**
 * DebitConnectLoginParametersTest Class Doc Comment
 *
 * @category    Class
 * @description DebitConnectLoginParameters
 * @package     VOP\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DebitConnectLoginParametersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DebitConnectLoginParameters"
     */
    public function testDebitConnectLoginParameters()
    {
    }

    /**
     * Test attribute "internal_id1"
     */
    public function testPropertyInternalId1()
    {
    }

    /**
     * Test attribute "internal_id2"
     */
    public function testPropertyInternalId2()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "bonigateway"
     */
    public function testPropertyBonigateway()
    {
    }
}
