<?php
/**
 * GetInformationResponseParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VOP\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * V.O.P GmbH & Co. KG - Rest API
 *
 * Rest API-Endpoint
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VOP\Rest;

/**
 * GetInformationResponseParametersTest Class Doc Comment
 *
 * @category    Class
 * @description GetInformationResponseParameters
 * @package     VOP\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetInformationResponseParametersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetInformationResponseParameters"
     */
    public function testGetInformationResponseParameters()
    {
    }

    /**
     * Test attribute "client_reference"
     */
    public function testPropertyClientReference()
    {
    }

    /**
     * Test attribute "debt_amount"
     */
    public function testPropertyDebtAmount()
    {
    }

    /**
     * Test attribute "fee"
     */
    public function testPropertyFee()
    {
    }

    /**
     * Test attribute "interest"
     */
    public function testPropertyInterest()
    {
    }

    /**
     * Test attribute "target_iban"
     */
    public function testPropertyTargetIban()
    {
    }

    /**
     * Test attribute "purpose"
     */
    public function testPropertyPurpose()
    {
    }

    /**
     * Test attribute "email_date"
     */
    public function testPropertyEmailDate()
    {
    }
}
