<?php
/**
 * NewOrderInputParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VOP\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * V.O.P GmbH & Co. KG - Rest API
 *
 * Rest API-Endpoint
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VOP\Rest;

/**
 * NewOrderInputParametersTest Class Doc Comment
 *
 * @category    Class
 * @description NewOrderInputParameters
 * @package     VOP\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NewOrderInputParametersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NewOrderInputParameters"
     */
    public function testNewOrderInputParameters()
    {
    }

    /**
     * Test attribute "ordertype"
     */
    public function testPropertyOrdertype()
    {
    }

    /**
     * Test attribute "catalogue_number"
     */
    public function testPropertyCatalogueNumber()
    {
    }

    /**
     * Test attribute "software"
     */
    public function testPropertySoftware()
    {
    }

    /**
     * Test attribute "debtor_information"
     */
    public function testPropertyDebtorInformation()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "invoice"
     */
    public function testPropertyInvoice()
    {
    }

    /**
     * Test attribute "correction"
     */
    public function testPropertyCorrection()
    {
    }

    /**
     * Test attribute "payments"
     */
    public function testPropertyPayments()
    {
    }

    /**
     * Test attribute "additional_text_information"
     */
    public function testPropertyAdditionalTextInformation()
    {
    }
}
