<?php
/**
 * PaymentTransactionDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VOP\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * V.O.P GmbH & Co. KG - Rest API
 *
 * Rest API-Endpoint
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VOP\Rest;

/**
 * PaymentTransactionDetailTest Class Doc Comment
 *
 * @category    Class
 * @description PaymentTransactionDetail
 * @package     VOP\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentTransactionDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentTransactionDetail"
     */
    public function testPaymentTransactionDetail()
    {
    }

    /**
     * Test attribute "internal_ids"
     */
    public function testPropertyInternalIds()
    {
    }

    /**
     * Test attribute "case_year"
     */
    public function testPropertyCaseYear()
    {
    }

    /**
     * Test attribute "case_number"
     */
    public function testPropertyCaseNumber()
    {
    }

    /**
     * Test attribute "invoice_year"
     */
    public function testPropertyInvoiceYear()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "payment_amount"
     */
    public function testPropertyPaymentAmount()
    {
    }

    /**
     * Test attribute "dunning_costs"
     */
    public function testPropertyDunningCosts()
    {
    }

    /**
     * Test attribute "input_tax"
     */
    public function testPropertyInputTax()
    {
    }
}
