<?php
/**
 * VopInvoiceDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VOP\Rest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * V.O.P GmbH & Co. KG - Rest API
 *
 * Rest API-Endpoint
 *
 * OpenAPI spec version: 3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VOP\Rest;

/**
 * VopInvoiceDetailTest Class Doc Comment
 *
 * @category    Class
 * @description VopInvoiceDetail
 * @package     VOP\Rest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VopInvoiceDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VopInvoiceDetail"
     */
    public function testVopInvoiceDetail()
    {
    }

    /**
     * Test attribute "mingeb"
     */
    public function testPropertyMingeb()
    {
    }

    /**
     * Test attribute "maxgeb"
     */
    public function testPropertyMaxgeb()
    {
    }

    /**
     * Test attribute "gebtext"
     */
    public function testPropertyGebtext()
    {
    }

    /**
     * Test attribute "gebuehr"
     */
    public function testPropertyGebuehr()
    {
    }

    /**
     * Test attribute "gebuehr1"
     */
    public function testPropertyGebuehr1()
    {
    }

    /**
     * Test attribute "rownumber"
     */
    public function testPropertyRownumber()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
